#!/bin/bash

clear

echo " Hi!, installing ROUS dependencies..."

apt-get update
apt-get install -y cups 
apt-get install -y python-cups 
apt-get install -y python-pip
apt-get -y dist-upgrade
curl -sL https://deb.nodesource.com/setup_8.x
apt-get install -y nodejs


if [ $( stat --printf="%s" requirements.txt ) -gt 0 ]
then
    pip install -r requirements.txt 
else
    printf "No requirments necessary\n"
fi


npm install -g -y create-react-app